#!/bin/bash
# Compose _parts/ into SKILL.md, driven by _parts/manifest.txt.
# Run automatically by `make install`. 
# Edit files under _parts/, not SKILL.md.

set -eu

cd "$(dirname "$0")"
PARTS="_parts"
MANIFEST="$PARTS/manifest.txt"
BUILD_DIR="build"
OUT="$BUILD_DIR/SKILL.md"

[ -f "$MANIFEST" ] || { echo "Error: $MANIFEST not found." >&2; exit 1; }
mkdir -p "$BUILD_DIR"

{
    echo "---"
    cat "$PARTS/frontmatter.yml"
    echo "---"
    echo ""
    echo "<!-- GENERATED FROM _parts/. DO NOT EDIT THIS FILE. -->"
    echo "<!-- Edit files in _parts/ and run \`make install\` (or \`bash skill/build.sh\`). -->"
    echo ""

    while IFS= read -r path; do
        # Strip leading/trailing whitespace
        path="${path#"${path%%[![:space:]]*}"}"
        path="${path%"${path##*[![:space:]]}"}"
        # Skip blanks, comments, and the frontmatter entry (handled above)
        case "$path" in
            ""|"#"*|"frontmatter.yml") continue ;;
        esac
        [ -f "$PARTS/$path" ] || { echo "Error: $PARTS/$path missing (referenced in manifest)." >&2; exit 1; }
        cat "$PARTS/$path"
        echo ""
    done < "$MANIFEST"
} > "$OUT"

echo "Built $OUT from $PARTS/ (driven by manifest.txt)"
